### ISSUE TITLE
decide how / how frequently to sync event details from AN to Affinity

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#10]
And setup recurring script at that frequency to syncing with action network.

**Comment by rabble** [comment]
We need to setup on heroku or  something to run a script which for each group imports new people, events, and attendances. Right now it just imports everything, so we need to track the last imported time, and get only things which are new or modified since last import. AN does let us order the collections by time so we should be able to do this.

**Comment by matinieves** [comment]
We are using Heroku Scheduler, the rake task run every hour.
